
//! Autogenerated weights for `peaq_pallet_did`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2022-09-30, STEPS: `20`, REPEAT: 10, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("agung"), DB CACHE: 1024

// Executed Command:
// ./target/release/peaq-node
// benchmark
// pallet
// --chain
// agung
// --execution
// wasm
// --wasm-execution
// compiled
// --pallet
// peaq_pallet_did
// --extrinsic
// *
// --steps
// 20
// --repeat
// 10
// --output
// weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::Weight};
use sp_std::marker::PhantomData;

/// Weight functions needed for peaq_pallet_transaction.
pub trait WeightInfo {
	fn add_attribute() -> Weight;
	fn update_attribute() -> Weight;
	fn read_attribute() -> Weight;
	fn remove_attribute() -> Weight;
}


/// Weight functions for `peaq_pallet_did`.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	// Storage: PeaqDid AttributeStore (r:1 w:1)
	// Storage: Timestamp Now (r:1 w:0)
	// Storage: PeaqDid OwnerStore (r:0 w:1)
	fn add_attribute() -> Weight {
		Weight::from_ref_time(20_709_000 as u64)
			.saturating_add(T::DbWeight::get().reads(2 as u64))
			.saturating_add(T::DbWeight::get().writes(2 as u64))
	}
	// Storage: PeaqDid OwnerStore (r:1 w:0)
	// Storage: PeaqDid AttributeStore (r:1 w:1)
	fn update_attribute() -> Weight {
		Weight::from_ref_time(23_815_000 as u64)
			.saturating_add(T::DbWeight::get().reads(2 as u64))
			.saturating_add(T::DbWeight::get().writes(1 as u64))
	}
	// Storage: PeaqDid AttributeStore (r:1 w:0)
	fn read_attribute() -> Weight {
		Weight::from_ref_time(16_582_000 as u64)
			.saturating_add(T::DbWeight::get().reads(1 as u64))
	}
	// Storage: PeaqDid OwnerStore (r:1 w:0)
	// Storage: PeaqDid AttributeStore (r:1 w:1)
	fn remove_attribute() -> Weight {
		Weight::from_ref_time(19_998_000 as u64)
			.saturating_add(T::DbWeight::get().reads(2 as u64))
			.saturating_add(T::DbWeight::get().writes(1 as u64))
	}
}
